# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zeal Desai | For Life 
email: zealdesai@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Zeal (as in New ZEALand) means enthusiasm. Ever since I left my corporate job, I have been in the process of living up to my name through teaching yoga as a way of life, curating a slow-fashion brand Zealia, and creating a social impact through Green Periods.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-compose

plugins: [jekyll-paginate]

paginate: 6
paginate_path: "blog/page:num"
